### ISSUE TITLE
表示感谢，顺便提点请求

### ISSUE THREAD

**Issue by 5starvip** [wxydejoy/MoneyProgress_win#4]
找了好久win版的，终于发现作者的这款软件，特意注册账户评论表示感谢。
另外，希望添加在 windows 状态栏显示赚了多少钱的动态信息，像那个 mac 版的软件一样，那就太好了。
再次表达感谢，找到你的网站了，但没法评论，只能来这里了，哈哈

**Comment by 5starvip** [comment]
如果可以，能加个好友就最好了，哈哈，方便了解最新开发进度。
vx： havegoodomen

**Comment by wxydejoy** [comment]
@5starvip 收到反馈,我研究一下

**Comment by wxydejoy** [comment]
@5starvip  新版本已经发布,欢迎提新的需求

**Comment by 5starvip** [comment]
太好了，明天下载试试！😀

weiekko ***@***.***> 于 2023年5月7日 下午9:36写道：


@5starvip<https://github.com/5starvip> 新版本已经发布,欢迎提新的需求
