### ISSUE TITLE
文本颜色自定义&文本内容可修改防隐私泄露

### ISSUE THREAD

**Issue by 5starvip** [wxydejoy/MoneyProgress_win#5]
现在的黄色字体放在白色的任务栏，几乎看不清文字；
文本内容可以自定义，比如可以自己编辑成：今日累计赚取金币 162 块；这样别人看到就不会以为是工资，进而泄露隐私之类。
感谢作者及时升级

**Comment by wxydejoy** [comment]
已经更新
