### ISSUE TITLE
任务栏图标相关的小建议

### ISSUE THREAD

**Issue by PlaneJ** [wxydejoy/MoneyProgress_win#6]
![image](https://github.com/wxydejoy/MoneyProgress_win/assets/40061060/31f7f530-a4b8-4598-9220-36ad3b8f698b)
希望可以隐藏图标，只保留文字，因为我觉得放在搜索栏这里很不错；
金额保留到小数点后两位。
谢谢大佬开发的这款工具，上班更有动力了呢(●'◡'●)

**Comment by wxydejoy** [comment]
确实隐藏的很到位,我调一下

**Comment by wxydejoy** [comment]
已经完成,请看最新的release

**Comment by PlaneJ** [comment]
感谢，可以添加个开机启动功能吗？

**Comment by PlaneJ** [comment]
> 已经完成,请看最新的release

感谢，可以添加个开机启动功能吗？

**Comment by wxydejoy** [comment]
@PlaneJ 
1、按下win+R快捷键，打开运行窗口，输入shell:startup，点击确定

2、打开启动文件夹，最后把想要添加的启动项快捷方式直接拖进这个文件夹

3、然后就可以看到我们将qq设置为启动项了。

4、我们还可以进入任务管理器中看看我们有没有添加成功。

**Comment by PlaneJ** [comment]
> @PlaneJ 1、按下win+R快捷键，打开运行窗口，输入shell:startup，点击确定
> 
> 2、打开启动文件夹，最后把想要添加的启动项快捷方式直接拖进这个文件夹
> 
> 3、然后就可以看到我们将qq设置为启动项了。
> 
> 4、我们还可以进入任务管理器中看看我们有没有添加成功。

这个方法试过了没有成功，不确定是不是我机子的问题

**Comment by wxydejoy** [comment]
@PlaneJ 那就试试任务计划程序 
https://www.bilibili.com/read/cv22276944
