### ISSUE TITLE
工作天数无法保存为小数

### ISSUE THREAD

**Issue by moyanyuansu** [wxydejoy/MoneyProgress_win#8]
因为有的月份工作是20，有的是21，有的是22，所以我就直接设置为劳动法规定的21.75天
工作天数可以设置为小数，计算都正常，但是关闭后再打开就会四舍五入，无法保存为小数，每次都要重新设置一次

**Comment by wxydejoy** [comment]
收到 这周末改一下

**Comment by wxydejoy** [comment]
已修复
